# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: S1AutoBackup

on: 
  # workflow_dispatch:
  push
jobs:

  # UpdateS1:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: CheckoutRepo
  #     uses: actions/checkout@v2
  #     with:
  #       ref: master
  #   - name: Set up Python
  #     uses: actions/setup-python@v2
  #     with:
  #       python-version: '3.x'
  #   - name: Install dependencies
  #     run: |
  #       python -m pip install --upgrade pip
  #       pip install setuptools wheel twine bs4 aiohttp requests
  #   - name: AddThreads
  #     env:
  #       S1_COOKIE: ${{ secrets.S1_COOKIE }}
  #     run: |
  #       python autorun.py
  #   - name: S1
  #     env:
  #       S1_COOKIE: ${{ secrets.S1_COOKIE }}
  #     run: |
  #       python s1.py
  #   - name: commit
  #     env:
  #       TZ: 'CST-8'
  #     run: |
  #       sudo timedatectl set-timezone Asia/Shanghai
  #       git config --global user.email trembleafterme@outlook.com
  #       git config --global user.name TomoeMami
  #       datime=$(date "+%Y年%m月%d日 %H:%M")
  #       echo "git commit: 上传于 $datime"
  #       if [ -n "$(git status -s)" ];then
  #           git add .
  #           git commit -m "[UpdateS1] 上传于 $datime" -a
  #       fi
  #   - name: Push changes
  #     uses: ad-m/github-push-action@master
  #     with:
  #       github_token: ${{ secrets.GITHUB_TOKEN }}
  PushS1B:
    # needs: UpdateS1
    runs-on: ubuntu-latest
    steps:
    - name: CheckoutRepo
      uses: actions/checkout@v2
      with:
        ref: master
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine pathlib
    - name: DataGenerate
      run: |
        python ./data.py
    - name: Pushes S1B folder
      uses: crykn/copy_folder_to_another_repo_action@v1.0.6
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_folder: S1B
        destination_repo: TomoeMami/tomoemami.github.io
        destination_folder: S1B
        user_email: 'trembleafterme@outlook.com'
        user_name: 'TomoeMami'
        commit_msg: '[GHA] Update the S1B files.'
